GoogleMapsTest/Controllers/FlightPointsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoogleMapsTest.Models;

namespace GoogleMapsTest.Controllers
{
    public class FlightPointsController : Controller
    {
        private LocaDatabase db = new LocaDatabase();

        // GET: FlightPoints
        public ActionResult Index()
        {
            var flightPoints = db.FlightPoints.Include(f => f.Mission);
            return View(flightPoints.ToList());
        }

        // GET: FlightPoints/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightPoint flightPoint = db.FlightPoints.Find(id);
            if (flightPoint == null)
            {
                return HttpNotFound();
            }
            return View(flightPoint);
        }

        // GET: FlightPoints/Create
        public ActionResult Create()
        {
            ViewBag.MissionFK = new SelectList(db.Missions, "MissionPK", "Name");
            var Model = new FlightPoint()
            {
                Altitude = 30,
                Target_yaw = 0,
                Damping_distance = 0,
                Target_gimbal_pitch = 0,
                Turn_mode = TurnMode.Clockwise,
                Has_action = HasAction.No_Action,
                Action_time_limit = 5,
                ACTION_action_repeat = 1,
                _ACTION_COMMAND_LIST = "1",
                _ACTION_COMMAND_PARAMS = "1"
                 
            };
            return View(Model);
        }

        // POST: FlightPoints/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FlightPointPK,MissionFK,Latitude,Longitude,Altitude,Damping_distance,Target_yaw,Target_gimbal_pitch,Turn_mode,Has_action,Action_time_limit,ACTION_action_repeat,_ACTION_COMMAND_LIST,_ACTION_COMMAND_PARAMS,PIAction")] FlightPoint flightPoint)
        {
            if (ModelState.IsValid)
            {
                db.FlightPoints.Add(flightPoint);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MissionFK = new SelectList(db.Missions, "MissionPK", "Name", flightPoint.MissionFK);
            return View(flightPoint);
        }

        // GET: FlightPoints/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightPoint flightPoint = db.FlightPoints.Find(id);
            if (flightPoint == null)
            {
                return HttpNotFound();
            }
            ViewBag.MissionFK = new SelectList(db.Missions, "MissionPK", "Name", flightPoint.MissionFK);
            return View(flightPoint);
        }

        // POST: FlightPoints/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FlightPointPK,MissionFK,Latitude,Longitude,Altitude,Damping_distance,Target_yaw,Target_gimbal_pitch,Turn_mode,Has_action,Action_time_limit,ACTION_action_repeat,_ACTION_COMMAND_LIST,_ACTION_COMMAND_PARAMS,PIAction")] FlightPoint flightPoint)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flightPoint).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MissionFK = new SelectList(db.Missions, "MissionPK", "Name", flightPoint.MissionFK);
            return View(flightPoint);
        }

        // GET: FlightPoints/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightPoint flightPoint = db.FlightPoints.Find(id);
            if (flightPoint == null)
            {
                return HttpNotFound();
            }
            return View(flightPoint);
        }

        // POST: FlightPoints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            FlightPoint flightPoint = db.FlightPoints.Find(id);
            db.FlightPoints.Remove(flightPoint);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetLastMissionPoint(long MissionPK)
        {
            var point = db.FlightPoints.Where(f => f.MissionFK == MissionPK).OrderByDescending(o => o.FlightPointPK).FirstOrDefault();
            if (point != null)
            { return Json(new { Latitude = point.Latitude, Longitude = point.Longitude, Altitude = point.Altitude, Action = (int)point.PIAction }, JsonRequestBehavior.AllowGet); }
            else { return null; }

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoogleMapsTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Missions", "Index", "Missions")</li>
                    <li>@Html.ActionLink("PolygonMissions", "PolygonMission", "Missions")</li>
                    <li>@Html.ActionLink("Flight Points", "Index", "FlightPoints")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    
</body>
</html>